# Upstream changes from _extends are only recognized when modifications are made to this file in the default branch.
_extends: .github
repository:
  name: terraform-aws-nlb
  description: Terraform module to provision a standard NLB for TCP/UDP/TLS traffic https://cloudposse.com/accelerate
  homepage: https://cloudposse.com/accelerate
  topics: ""


